import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/Banner'
import BlogCard from '../components/BlogCard/BlogCard'
import Wrapper from '../components/Wrapper'
import {data} from '../lib/data'
import {AiOutlineArrowRight} from 'react-icons/ai'

export default function Home({blogs}) {
  return (
    <Wrapper>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full flex flex-col items-center flex-1">
        <Banner />
        <div className="w-5/6 my-4">
          <div className="grid md:grid-cols-2 lg:grid-cols-3  gap-4 ">
            {blogs.map(blog => (
              <BlogCard blog={blog} key={blog.slug} />
            ))}
          </div>
        </div>

        <div className="my-4 ">
          <button className="py-3 px-6 bg-yellow-400 hover:bg-yellow-500 font-semibold rounded-lg text-xl flex items-center justify-between">
            More <AiOutlineArrowRight className="ml-3" size="28px" />
          </button>
        </div>
      </main>

      {/* <div className="h-96" /> */}
    </Wrapper>
  )
}

export async function getStaticProps(context) {
  // last 3 blogs
  const latestBlog = data.slice(data.length - 3)
  return {
    props: {
      blogs: latestBlog,
    }, // will be passed to the page component as props
  }
}
