import Head from 'next/head'
import Image from 'next/image'
import {data} from '../lib/data'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>My Blogs</h1>

        <div>
          {data.map(blog => {
            return (
              <div key={blog.slug}>
                <div>{blog.slug}</div>
                <div>{blog.title}</div>
                <div>{blog.author}</div>
                <br />
              </div>
            )
          })}
        </div>
      </main>
    </div>
  )
}
